"""add summary column to skills

Revision ID: 0aaebfe4228f
Revises: 3f9c2b0e1b6a
Create Date: 2026-02-10 14:30:38.066398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aaebfe4228f'
down_revision: Union[str, None] = '3f9c2b0e1b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('summary', sa.Text(), nullable=True))
    op.drop_constraint(op.f('system_settings_key_key'), 'system_settings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('system_settings_key_key', 'system_settings', ['key'])
    op.drop_column('skills', 'summary')
    # ### end Alembic commands ###
