"""Add embedding column

Revision ID: 5c9349039f96
Revises: cf1d3d8a123e
Create Date: 2026-02-12 10:33:54.584263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '5c9349039f96'
down_revision: Union[str, None] = 'cf1d3d8a123e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.drop_constraint(op.f('system_settings_key_key'), 'system_settings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('system_settings_key_key'), 'system_settings', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_column('skills', 'embedding')
    # ### end Alembic commands ###
