"""add overview column to skills

Revision ID: cf1d3d8a123e
Revises: 0aaebfe4228f
Create Date: 2026-02-11 17:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1d3d8a123e'
down_revision: Union[str, None] = '0aaebfe4228f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('skills')]
    if 'overview' not in columns:
        op.add_column('skills', sa.Column('overview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'overview')
    # ### end Alembic commands ###
